search_string = 'prodej/byt'
res_final = []
res =['https://play.google.com/store/apps/details?id=cz.seznam.sreality', 'https://www.sreality.cz/',
      'https://www.sreality.cz/en/search/for-sale/apartments?page=100', 'https://www.sreality.cz/ru/search/for-sale/apartments?page=100',
      'https://www.seznam.cz/', 'https://login.szn.cz/?service=sreality&return_url=https%3A%2F%2Fwww.sreality.cz%2Fhledani%2Fprodej%2Fbyty%3Fstrana%3D100&lang=cs',
      'https://www.sreality.cz/detail/prodej/byt/3+kk/brno-kralovo-pole-kostelni-zmola/1521237596', 'https://www.sreality.cz/detail/prodej/byt/3+1/brno-komin-podlesi/2013806172',
      'https://www.sreality.cz/detail/prodej/byt/3+kk/brno--lisejnikova/575442524',
      'https://www.sreality.cz/detail/prodej/byt/4+kk/brno--lisejnikova/843877980',
      'https://www.sreality.cz/detail/prodej/byt/1+1/plzen-bolevec-gerska/1201421916', 'https://www.sreality.cz/detail/prodej/byt/2+1/rybitvi-rybitvi-cinzovnich-domu/508116572',
      'https://www.sreality.cz/detail/prodej/byt/3+kk/praha-stodulky-modra/551669340', 'https://www.sreality.cz/detail/prodej/byt/2+kk/praha-chodov-babakova/1760181852',
      'https://www.sreality.cz/detail/prodej/byt/3+kk/ceske-budejovice-ceske-budejovice-2-/3617341020',
      'https://www.sreality.cz/detail/prodej/byt/3+1/zdounky-zdounky-nadrazni/776552028',
      'https://www.sreality.cz/detail/prodej/byt/2+1/svitavy-predmesti-marie-pujmanove/1782136412', 'https://www.sreality.cz/detail/prodej/byt/1+kk/praha-vrsovice-belocerkevska/1956396636', 'https://www.sreality.cz/detail/prodej/byt/3+kk/praha-stodulky-petrzilkova/2860699228', 'https://www.sreality.cz/adresar/duna-house-franchise-s-r-o-praha-michle/19696', 'https://www.sreality.cz/detail/prodej/byt/4+1/jablonec-nad-nisou-mseno-nad-nisou-prazskeho-povstani/3079143004', 'https://www.sreality.cz/adresar/re-max-gold-jablonec-nad-nisou/14001', 'https://www.sreality.cz/detail/prodej/byt/2+kk/kladno-krocehlavy-generala-selnera/1065303644', 'https://www.sreality.cz/detail/prodej/byt/2+1/mlada-boleslav-mlada-boleslav-ii-erbenova/2038971996', 'https://www.sreality.cz/detail/prodej/byt/3+1/pardubice-studanka-erno-kostala/933772892', 'https://www.sreality.cz/adresar/clever-properties-s-r-o-pardubice-bile-predmesti/17082', 'https://www.sreality.cz/detail/prodej/byt/1+kk/praha-sterboholy-pod-arealem/2457812572', 'https://www.sreality.cz/detail/prodej/byt/3+kk/praha-karlin-za-karlinskym-pristavem/2828746332', 'https://www.sreality.cz/detail/prodej/byt/2+kk/praha-stodulky-svitakova/3549810268', 'https://napoveda.seznam.cz/cz/sreality/zasady-zpracovani-osobnich-udaju-sreality/', 'https://www.sreality.cz/hledani/prodej/byty?strana=99', 'https://www.sreality.cz/hledani/prodej/byty', 'https://www.sreality.cz/hledani/prodej/byty?strana=96', 'https://www.sreality.cz/hledani/prodej/byty?strana=97', 'https://www.sreality.cz/hledani/prodej/byty?strana=98', 'https://www.sreality.cz/hledani/prodej/byty?strana=100', 'https://www.sreality.cz/hledani/prodej/byty?strana=101', 'https://www.sreality.cz/hledani/prodej/byty?strana=102', 'https://www.sreality.cz/hledani/prodej/byty?strana=103', 'https://www.sreality.cz/hledani/prodej/byty?strana=104', 'https://vyzkumnik.seznam.cz/', 'https://napoveda.seznam.cz/cz/sreality/pravidla-sreality/vseobecne-obchodni-podminky/vop-pro-vkladani-jednorazove-inzerce-do-databaze-sreality/#spotrebitel', 'https://www.seznam.cz/ochranaudaju', 'https://napoveda.seznam.cz/cz/sreality/pravidla-sreality/vseobecne-obchodni-podminky/', 'https://www.seznam.cz/reklama/cz/obsahovy-web/sluzba-sreality', 'https://www.sreality.cz/realitni-software', 'http://sreality.seznamblog.cz/', 'https://napoveda.seznam.cz/cz/sreality/', 'mailto:info@sreality.cz?subject=Dotaz ze sluzby sreality.cz', 'https://napoveda.seznam.cz/cz/sreality/kontakty-sreality-cz/', 'https://o.seznam.cz/', 'https://www.openstreetmap.org/copyright', 'https://mapy.cz/?x=15.488097&y=49.794049&z=6']
for x in res:
    if search_string in x:
        res_final.append(x)
print(res_final)