CREATE TABLE `dbrealtor`.`byty` (
  `id` INT NOT NULL,
  `title` VARCHAR(400) NULL,
  `type` VARCHAR(45) NULL,
  `celkova_cena` VARCHAR(200) NULL,
  `poznamka_k_cene` VARCHAR(150) NULL,
  `cena` INT NULL,
  `naklady` VARCHAR(45) NULL,
  `id_ext` INT NULL,
  `actualizace` VARCHAR(45) NULL,
  `stavba` VARCHAR(45) NULL COMMENT 'state of object',
  `stav_objectul` VARCHAR(45) NULL,
  `valsnictvi` VARCHAR(45) NULL,
  `podlazi` VARCHAR(150) NULL,
  `uzitna_plocha` VARCHAR(45) NULL,
  `terasa` VARCHAR(45) NULL,
  `sklep` VARCHAR(45) NULL,
  `datum_nastegovani` VARCHAR(45) NULL,
  `rok_kolaudace` VARCHAR(45) NULL,
  `rok_reconstrukce` VARCHAR(45) NULL,
  `voda` VARCHAR(45) NULL,
  `topeni` VARCHAR(45) NULL,
  `odpad` VARCHAR(45) NULL,
  `telekomunikace` VARCHAR(150) NULL,
  `elaktrina` VARCHAR(20) NULL,
  `doprava` VARCHAR(100) NULL,
  `komunikace` VARCHAR(45) NULL,
  `energ_narocnost_budovy` VARCHAR(45) NULL,
  `bezbarierovy` VARCHAR(10) NULL,
  `vybaveni` VARCHAR(45) NULL,
  `vytah` VARCHAR(10) NULL,
  `kontakt` VARCHAR(200) NULL,
  `date_add` DATETIME(6) NULL,
  `bytycol` VARCHAR(45) NULL,
  `decription` VARCHAR(1000) NULL
  PRIMARY KEY (`idbyty`),
  UNIQUE INDEX `idbyty_UNIQUE` (`idbyty` ASC) VISIBLE)
COMMENT = 'Table for appartments';
