CREATE TABLE `byty` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(400) DEFAULT NULL,
  `typ_bytu` varchar(45) DEFAULT NULL,
  `celkova_cena` varchar(200) DEFAULT NULL,
  `poznamka_k_cene` varchar(150) DEFAULT NULL,
  `cena` int(11) DEFAULT NULL,
  `naklady` varchar(45) DEFAULT NULL,
  `id_ext` varchar(45) DEFAULT NULL COMMENT 'ID from external system',
  `aktualizace` varchar(45) DEFAULT NULL,
  `stavba` varchar(45) DEFAULT NULL COMMENT 'state of object',
  `stav_objectu` varchar(45) DEFAULT NULL,
  `vlastnictvi` varchar(45) DEFAULT NULL,
  `podlazi` varchar(150) DEFAULT NULL,
  `uzitna_plocha` varchar(45) DEFAULT NULL,
  `terasa` varchar(45) DEFAULT NULL,
  `sklep` varchar(45) DEFAULT NULL,
  `datum_nastegovani` varchar(45) DEFAULT NULL,
  `rok_kolaudace` varchar(45) DEFAULT NULL,
  `rok_reconstrukce` varchar(45) DEFAULT NULL,
  `voda` varchar(45) DEFAULT NULL,
  `topeni` varchar(45) DEFAULT NULL,
  `odpad` varchar(45) DEFAULT NULL,
  `telekomunikace` varchar(150) DEFAULT NULL,
  `elektrina` varchar(20) DEFAULT NULL,
  `doprava` varchar(100) DEFAULT NULL,
  `komunikace` varchar(45) DEFAULT NULL,
  `energ_narocnost_budovy` varchar(150) DEFAULT NULL,
  `bezbarierovy` varchar(10) DEFAULT NULL,
  `vybaveni` varchar(45) DEFAULT NULL,
  `vytah` varchar(10) DEFAULT NULL,
  `kontakt` varchar(200) DEFAULT NULL,
  `description` varchar(4000) DEFAULT NULL,
  `link` varchar(500) DEFAULT NULL,
  `date_add` datetime DEFAULT NULL,
  `umisteni_objektu` varchar(45) DEFAULT NULL,
  `parkovani` varchar(5) DEFAULT NULL,
  `puvodni_cena` varchar(200) DEFAULT NULL,
  `region` varchar(200) DEFAULT NULL,
  `subregion` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idbyty_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Table for appartments';

CREATE TABLE `domy_prodej` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`id_load` INT(11) NULL DEFAULT NULL,
	`link` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`date_open` DATETIME NULL DEFAULT NULL,
	`date_update` DATETIME NULL DEFAULT NULL,
	`date_close` DATETIME NULL DEFAULT NULL,
	`status` VARCHAR(1) NULL DEFAULT 'O' COLLATE 'utf8mb4_general_ci',
	`obj_number` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`region` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`subregion` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`title` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`description` VARCHAR(4000) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`puvodni_cena` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`celkova_cena` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`poznamka_k_cene` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`cena` INT(11) NULL DEFAULT NULL,
	`naklady` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`id_ext` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ID zakazky' COLLATE 'utf8mb4_general_ci',
	`aktualizace` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`stavba` VARCHAR(45) NULL DEFAULT NULL COMMENT 'state of object' COLLATE 'utf8mb4_general_ci',
	`stav_objektu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`umisteni_objektu:` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`typ_domu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`vlastnictvi` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`podlazi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`pocet_bytu` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_domu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_zastavena` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`uzitna_plocha` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_podlahova` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_pozemku` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_zahrady` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`parkovani` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`garaz` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`terasa` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`sklep` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`datum_nastegovani` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`rok_kolaudace` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`rok_reconstrukce` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`voda` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`topeni` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plyn` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`odpad` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`telekomunikace` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`elektrina` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`doprava` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`komunikace` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`energ_narocnost_budovy` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`bezbarierovy` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`vybaveni` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`bazen` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`umisteni_objektu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`kontakt` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `idbyty_UNIQUE` (`id`)
)
COMMENT='Table for prodej domu'
ENGINE=InnoDB
;


CREATE TABLE `domy_pronajem` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`id_load` INT(11) NOT NULL DEFAULT '0',
	`title` VARCHAR(250) NULL DEFAULT NULL,
	`obj_number` VARCHAR(250) NULL DEFAULT NULL,
	`date_open` DATETIME NULL DEFAULT NULL,
	`date_update` DATETIME NULL DEFAULT NULL,
	`date_close` DATETIME NULL DEFAULT NULL,
	`status` VARCHAR(1) NULL DEFAULT NULL,
	`cena` INT(11) NULL DEFAULT NULL,
	`celkova_cena` VARCHAR(100) NULL DEFAULT NULL,
	`poznamka_k_cene` VARCHAR(300) NULL DEFAULT NULL,
	`puvodni_cena` VARCHAR(100) NULL DEFAULT NULL,
	`description` VARCHAR(3000) NULL DEFAULT NULL,
	`link` VARCHAR(300) NULL DEFAULT NULL,
	`region` VARCHAR(100) NULL DEFAULT NULL,
	`subregion` VARCHAR(100) NULL DEFAULT NULL,
	`aktualizace` VARCHAR(25) NULL DEFAULT NULL,
	`id_ext` VARCHAR(25) NULL DEFAULT NULL,
	`stavba` VARCHAR(25) NULL DEFAULT NULL,
	`stav_objektu` VARCHAR(25) NULL DEFAULT NULL,
	`vlastnictvi` VARCHAR(25) NULL DEFAULT NULL,
	`umisteni_objektu` VARCHAR(25) NULL DEFAULT NULL,
	`podlazi` VARCHAR(50) NULL DEFAULT NULL,
	`uzitna_plocha` VARCHAR(25) NULL DEFAULT NULL,
	`poloha_domu` VARCHAR(25) NULL DEFAULT NULL,
	`plocha_zastavena` VARCHAR(25) NULL DEFAULT NULL,
	`typ_domu` VARCHAR(25) NULL DEFAULT NULL,
	`plocha_pozemku` VARCHAR(25) NULL DEFAULT NULL,
	`plocha_zahrady` VARCHAR(25) NULL DEFAULT NULL,
	`rok_rekonstrukce` VARCHAR(10) NULL DEFAULT NULL,
	`terasa` VARCHAR(1) NULL DEFAULT NULL,
	`sklep` VARCHAR(100) NULL DEFAULT NULL,
	`voda` VARCHAR(100) NULL DEFAULT NULL,
	`topeni` VARCHAR(25) NULL DEFAULT NULL,
	`plyn` VARCHAR(25) NULL DEFAULT NULL,
	`odpad` VARCHAR(40) NULL DEFAULT NULL,
	`telekomunikace` VARCHAR(100) NULL DEFAULT NULL,
	`elektrina` VARCHAR(25) NULL DEFAULT NULL,
	`doprava` VARCHAR(100) NULL DEFAULT NULL,
	`komunikace` VARCHAR(25) NULL DEFAULT NULL,
	`vybaveni` VARCHAR(1) NULL DEFAULT NULL,
	`bezbarierovy` VARCHAR(1) NULL DEFAULT NULL,
	`bazen` VARCHAR(1) NULL DEFAULT NULL,
	`kontakt` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='Save all from pronajem SReality'
ENGINE=INNODB
;

CREATE TABLE `domy_pronajem` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`id_load` INT(11) NULL DEFAULT NULL,
	`link` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`date_open` DATETIME NULL DEFAULT NULL,
	`date_update` DATETIME NULL DEFAULT NULL,
	`date_close` DATETIME NULL DEFAULT NULL,
	`status` VARCHAR(1) NULL DEFAULT 'O' COLLATE 'utf8mb4_general_ci',
	`obj_number` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`region` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`subregion` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`title` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`description` VARCHAR(4000) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`puvodni_cena` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`celkova_cena` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`poznamka_k_cene` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`cena` INT(11) NULL DEFAULT NULL,
	`naklady` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`id_ext` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ID zakazky' COLLATE 'utf8mb4_general_ci',
	`aktualizace` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`stavba` VARCHAR(45) NULL DEFAULT NULL COMMENT 'state of object' COLLATE 'utf8mb4_general_ci',
	`stav_objektu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`umisteni_objektu:` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`typ_domu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`vlastnictvi` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`podlazi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`pocet_bytu` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_domu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_zastavena` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`uzitna_plocha` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_podlahova` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_pozemku` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plocha_zahrady` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`parkovani` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`garaz` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`terasa` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`sklep` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`datum_nastegovani` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`rok_kolaudace` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`rok_reconstrukce` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`voda` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`topeni` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`plyn` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`odpad` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`telekomunikace` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`elektrina` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`doprava` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`komunikace` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`energ_narocnost_budovy` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`bezbarierovy` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`vybaveni` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`bazen` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`umisteni_objektu` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`kontakt` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `idbyty_UNIQUE` (`id`)
)
COMMENT='Table for prodej domu'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
